---
apiVersion: v1
kind: Namespace
metadata:
  name: elk-test
---
#kubectl create secret docker-registry harbor-secret --docker-server= --docker-username= --docker-password='****' --docker-email=zliu@fortinet.com -n fcasb-test-rd
#echo -n "admin" | base64
apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: elk-test
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIzNC4yMTMuMTM3Ljk5Ojg4ODgiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2Um05eWRHbGtZakVoSkE9PSIKCQl9Cgl9Cn0=

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: %SERVICE_NAME%
  namespace: elk-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %SERVICE_NAME%
      type: %MODULE_NAME%
  template:
    metadata:
      labels:
        app: %SERVICE_NAME%
        type: %MODULE_NAME%
        env: test
        version: 1.0.0
        build: v_%BUILD_NUMBER%
    spec:
      containers:
        - name: %SERVICE_NAME%
          image: "%REPOSITORY_URI%:v_%BUILD_NUMBER%"
          ports:
            - name: http
              containerPort: 30080
      imagePullSecrets:
        - name: harbor-secret
---
kind: Service
apiVersion: v1
metadata:
  name: %SERVICE_NAME%
  namespace: elk-test
spec:
  type: NodePort
  selector:
    app: %SERVICE_NAME%
    type: %MODULE_NAME%
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 30080
      targetPort: 30080
      protocol: TCP
      name: http