---
apiVersion: v1
kind: Namespace
metadata:
  name: elk-test
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: monitor-alert
  namespace: elk-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %SERVICE_NAME%
      type: %MODULE_NAME%
      build: v_%BUILD_NUMBER%
  template:
    metadata:
      labels:
        app: %SERVICE_NAME%
        type: %MODULE_NAME%
        env: test
        version: 1.0.0
        build: v_%BUILD_NUMBER%
    spec:
      containers:
        - name: %SERVICE_NAME%
          image: "%REPOSITORY_URI%:v_%BUILD_NUMBER%"
          ports:
            - name: http
              containerPort: 30080
---
kind: Service
apiVersion: v1
metadata:
  name: monitor-alert
  namespace: elk-test
spec:
  type: NodePort
  selector:
    app: %SERVICE_NAME%
    type: %MODULE_NAME%
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 30080
      targetPort: 30080
      protocol: TCP
      name: http